/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ConsultationSuccessRouteImport } from './routes/consultation-success'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyCheckoutRouteImport } from './routes/api/verify-checkout'
import { Route as ApiRedesignRoomRouteImport } from './routes/api/redesign-room'
import { Route as ApiCreateCheckoutRouteImport } from './routes/api/create-checkout'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationSuccessRoute = ConsultationSuccessRouteImport.update({
  id: '/consultation-success',
  path: '/consultation-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyCheckoutRoute = ApiVerifyCheckoutRouteImport.update({
  id: '/api/verify-checkout',
  path: '/api/verify-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedesignRoomRoute = ApiRedesignRoomRouteImport.update({
  id: '/api/redesign-room',
  path: '/api/redesign-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateCheckoutRoute = ApiCreateCheckoutRouteImport.update({
  id: '/api/create-checkout',
  path: '/api/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consultation-success': typeof ConsultationSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/redesign-room': typeof ApiRedesignRoomRoute
  '/api/verify-checkout': typeof ApiVerifyCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consultation-success': typeof ConsultationSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/redesign-room': typeof ApiRedesignRoomRoute
  '/api/verify-checkout': typeof ApiVerifyCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/consultation-success': typeof ConsultationSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/redesign-room': typeof ApiRedesignRoomRoute
  '/api/verify-checkout': typeof ApiVerifyCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/consultation-success'
    | '/sitemap.xml'
    | '/projects'
    | '/api/chat'
    | '/api/create-checkout'
    | '/api/redesign-room'
    | '/api/verify-checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/consultation-success'
    | '/sitemap.xml'
    | '/projects'
    | '/api/chat'
    | '/api/create-checkout'
    | '/api/redesign-room'
    | '/api/verify-checkout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/consultation-success'
    | '/sitemap.xml'
    | '/_authenticated/projects'
    | '/api/chat'
    | '/api/create-checkout'
    | '/api/redesign-room'
    | '/api/verify-checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConsultationSuccessRoute: typeof ConsultationSuccessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCreateCheckoutRoute: typeof ApiCreateCheckoutRoute
  ApiRedesignRoomRoute: typeof ApiRedesignRoomRoute
  ApiVerifyCheckoutRoute: typeof ApiVerifyCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation-success': {
      id: '/consultation-success'
      path: '/consultation-success'
      fullPath: '/consultation-success'
      preLoaderRoute: typeof ConsultationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-checkout': {
      id: '/api/verify-checkout'
      path: '/api/verify-checkout'
      fullPath: '/api/verify-checkout'
      preLoaderRoute: typeof ApiVerifyCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/redesign-room': {
      id: '/api/redesign-room'
      path: '/api/redesign-room'
      fullPath: '/api/redesign-room'
      preLoaderRoute: typeof ApiRedesignRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-checkout': {
      id: '/api/create-checkout'
      path: '/api/create-checkout'
      fullPath: '/api/create-checkout'
      preLoaderRoute: typeof ApiCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConsultationSuccessRoute: ConsultationSuccessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCreateCheckoutRoute: ApiCreateCheckoutRoute,
  ApiRedesignRoomRoute: ApiRedesignRoomRoute,
  ApiVerifyCheckoutRoute: ApiVerifyCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
